import { Container } from "@components/Container";

export const metadata = {
  title: "AI Transparency — Cladex",
  description:
    "How Cladex uses artificial intelligence for real estate transaction decision support.",
};

export default function AITransparencyPage() {
  return (
    <Container>
      <div className="px-4 max-w-3xl mx-auto py-20 md:py-32">
        <p className="text-xs uppercase tracking-wider text-zinc-500 font-medium mb-2">
          LEGAL
        </p>
        <h1 className="font-display text-3xl tracking-tight text-zinc-900 sm:text-4xl md:text-5xl">
          AI Transparency & Responsible Use
        </h1>
        <p className="mt-4 text-lg tracking-tight text-zinc-600 leading-relaxed">
          Cladex uses artificial intelligence to assist users in understanding and organizing real estate transactions. AI is designed to provide decision-support insights, not decision-making authority.
        </p>

        <div className="mt-10 rounded-2xl border border-zinc-200 bg-zinc-50 px-8 py-8">
          <p className="text-lg tracking-tight text-zinc-700 leading-relaxed font-medium">
            AI-generated insights, comparisons, negotiation scripts, or risk indicators are automated informational tools only. They do not constitute legal advice, brokerage services, financial advice, or real estate valuation services. AI outputs may contain errors or incomplete information. Users must independently verify all information before acting on it.
          </p>
        </div>

        <section className="mt-12">
          <h2 className="text-xl font-display tracking-tight text-zinc-900 mt-8">
            AI Use Cases
          </h2>
          <p className="mt-4 text-lg tracking-tight text-zinc-600 leading-relaxed">
            AI systems within Cladex may assist with summarizing real estate documents, highlighting potential transaction risks, generating negotiation suggestions, analyzing timelines and workflow steps, and identifying missing documentation.
          </p>
        </section>

        <section className="mt-10">
          <h2 className="text-xl font-display tracking-tight text-zinc-900 mt-8">
            Important Limitations
          </h2>
          <ul className="mt-4 space-y-2 text-lg tracking-tight text-zinc-600 leading-relaxed list-disc list-inside">
            <li>AI outputs are probabilistic predictions</li>
            <li>May contain errors or omissions</li>
            <li>May not reflect local laws or regulations</li>
            <li>Should not be treated as professional advice</li>
            <li>Must be independently verified before reliance</li>
          </ul>
        </section>

        <section className="mt-10">
          <h2 className="text-xl font-display tracking-tight text-zinc-900 mt-8">
            Human Oversight
          </h2>
          <p className="mt-4 text-lg tracking-tight text-zinc-600 leading-relaxed">
            Cladex does not make decisions on behalf of users. All real estate decisions remain the responsibility of buyers, sellers, agents, and attorneys. AI assists with analysis — it does not replace licensed professional judgment.
          </p>
        </section>

        <section className="mt-10">
          <h2 className="text-xl font-display tracking-tight text-zinc-900 mt-8">
            Bias and Fairness
          </h2>
          <p className="mt-4 text-lg tracking-tight text-zinc-600 leading-relaxed">
            AI systems may reflect biases present in training data. Cladex works to reduce bias through testing, monitoring, and model improvements. However, bias-free outcomes cannot be guaranteed. Users should apply independent judgment to all AI-generated outputs.
          </p>
        </section>

        <section className="mt-10">
          <h2 className="text-xl font-display tracking-tight text-zinc-900 mt-8">
            Data Usage
          </h2>
          <p className="mt-4 text-lg tracking-tight text-zinc-600 leading-relaxed">
            User-provided data may be processed by automated systems to generate insights and recommendations. Cladex does not sell personal data. See our Privacy Policy for full details.
          </p>
        </section>

        <section className="mt-10">
          <h2 className="text-xl font-display tracking-tight text-zinc-900 mt-8">
            Risk Score Disclaimer
          </h2>
          <p className="mt-4 text-lg tracking-tight text-zinc-600 leading-relaxed">
            Risk scores and alerts are informational indicators generated by automated systems. They do not constitute professional legal, financial, or real estate advice. Risk indicators should be used as one input among many — not as the sole basis for transaction decisions.
          </p>
        </section>

        <div className="mt-16 rounded-2xl border border-zinc-200 bg-zinc-50 px-8 py-8">
          <p className="text-sm text-zinc-600 leading-relaxed">
            Cladex provides structured transaction workflow tools. We are not a real estate broker, attorney, escrow provider, or financial advisor. AI outputs are informational only.
          </p>
        </div>
        <p className="mt-6 text-sm text-zinc-500">
          Questions: legal@cladex.io
        </p>
      </div>
    </Container>
  );
}
